#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# build with Jekyll into "_site"
bundle exec jekyll build

# push
cd _site
git init
git config user.email "kartherrupnik@gmail.com"
git config user.name "echofatalerror"
git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git remote add origin https://github.com/echofatalerror/echofatalerror.github.io.git
git push --force origin master