#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# build with Jekyll into "_site"
bundle exec jekyll build

# push

git clone https://cf9e80f57e68a8644be130d788872da06a697b08@github.com/echofatalerror/echofatalerror.github.io.git _site

# build with Jekyll into "_site"
bundle exec jekyll build

cd _site
git config user.email "kartherrupnik@gmail.com"
git config user.name "echofatalerror"
git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push --force origin master

